### PR TITLE
FIX: window.crypto is not available in worker

### PR DESCRIPTION
**Pull request by k2s**
fixed based on this article https://stackoverflow.com/questions/13004375/running-window-crypto-getrandomvalues-from-inside-a-web-worker

### CODE REVIEW

**Comment by ericelliott** [comment]
Is there some way we can test this?

**Comment by k2s** [comment]
unfortunately I don't know how to automate WebWorker with Testcafe

**Comment by daikiuk** [comment]
Hi, any idea when will this be merged in?

**Comment by ericelliott** [comment]
> Hi, any idea when will this be merged in?

Have you tested this fix? Does it work for you?

**Comment by ericelliott** [comment]
If `window` does not exist, this code would produce:  `ReferenceError: window is not defined`.

This does not throw errors. Does it behave correctly?

```js
const crypto = typeof window !== 'undefined'
  && (window.crypto || window.msCrypto)
  || typeof self !== 'undefined'
  && self.crypto
;
```

**Comment by mspoulsen** [comment]
I am having the exact same issue. The suggested fix still produces `ReferenceError: window is not defined`

However, Eric's proposal works:
```javascript
const crypto = typeof window !== 'undefined'
  && (window.crypto || window.msCrypto)
  || typeof self !== 'undefined'
  && self.crypto
;
```
Please merge :slightly_smiling_face:

**Comment by ericelliott** [comment]
I have not thoroughly tested that logic.

**Comment by ericelliott** [comment]
We just need some tests for this now. Can we use TestCafe to make sure this works properly?

**Comment by daikiuk** [comment]
latest fix works in our project, unable to supply Testcafe test though

**Comment by ericelliott** [comment]
We need some automated test coverage of this feature to ensure that we're not breaking existing use-cases. I'll merge the changes and push an update as soon as we get coverage.

**Comment by k2s** [comment]
I was trying to add test for worker. I am not very skilled with testcafe, but my impression is that the current `testcafe chrome ./test/browser.js` test is not really executing `cuid()` in browser.

It starts chrome, but `t.ok(typeof cuid() === 'string'...)` is executing the `cuid()` function under nodejs and not inside the browser.

If this would be fixed in project setup, then it should be easy to use `new Worker()`.

**Comment by ericelliott** [comment]
You should be able to serve a page with a `cuid()` inside a worker, rather than in the test file.

**Comment by cbettinger** [comment]
Is there any chance this rather trivial bug gets fixed/merged?

**Comment by ericelliott** [comment]
@cbettinger All we're waiting on is a test. Please feel free to add a browser test for it.

**Comment by cbettinger** [comment]
I realized the tests and created a pull request to k2s/cuid.

**Comment by k2s** [comment]
@cbettinger thank you

**Pull request merged**
