### PR TITLE
Switch to testcafe for browser tests

### PR DESCRIPTION
**Pull request by kennylavender**
Switch to testcafe for browser tests because karma has marked vulnerabilities.

## Change Details

In order to avoid duplicate unit tests for the browser and server, I've wrapped the test file to take in a 'test' function and configuration instead of importing tape directly. This allows us to create a mapping function for test cafe to tape format so we can avoid the duplicate unit tests.

No tests where changed, just format adjusted to use async/await and arrow functions.

### eslint
- Added TestCafe eslint plugin to fix errors around the global `test` and `fixture` that TestCafe uses.
- Set `no-unused-expressions` to not error or warn anymore. TestCafe requires the use of `fixture` and it was causing this rule to error.
- Added env: es6 to allow the use of es6 features
- Added parserOption: ecmaVersion: to allow lint to correctly parse the test files.

### babel
Added babel so that we could use async/await inside the server test file.

### Removed node 4, added node 9
node 4 is not supported by TestCafe.

### Adjusted Travis setup to support TestCafe
http://devexpress.github.io/testcafe/documentation/recipes/integrating-testcafe-with-ci-systems/travis.html

### package.json scripts
`test:browser` and `test:server` now run their own specified files in the test directory.

### Removed test-worker.js
This seemed to be just a file to run the tape tests in the browser user Karma. No longer necessary with TestCafe.

### CODE REVIEW

**Comment by kennylavender** [comment]
Tests failed to run on travis, here is the relevant output. Might be due to node version 4. Might need to update node.

```
Updating nvm
nvm.install
2.76s$ nvm install 4
Downloading and installing node v4.9.1...
Downloading https://nodejs.org/dist/v4.9.1/node-v4.9.1-linux-x64.tar.xz...
Computing checksum with sha256sum
Checksums matched!
Now using node v4.9.1 (npm v2.15.11)
$ node --version
v4.9.1
$ npm --version
2.15.11
$ nvm --version
0.33.11
install.npm
40.77s$ npm install 
npm WARN engine testcafe@0.21.1: wanted: {"node":">=6.0.0"} (current: {"node":"4.9.1","npm":"2.15.11"})
npm WARN optional dep failed, continuing fsevents@1.2.4
npm WARN engine node-version@1.2.0: wanted: {"node":">=6.0.0"} (current: {"node":"4.9.1","npm":"2.15.11"})
npm WARN engine testcafe-hammerhead@14.2.4: wanted: {"node":">= 6.0.0"} (current: {"node":"4.9.1","npm":"2.15.11"})
mkdirp@0.5.1 node_modules/mkdirp
└── minimist@0.0.8
uglify-js@3.4.7 node_modules/uglify-js
├── commander@2.16.0
└── source-map@0.6.1
watchify@3.11.0 node_modules/watchify
├── defined@1.0.0
├── xtend@4.0.1
├── through2@2.0.3 (readable-stream@2.3.6)
├── outpipe@1.1.1 (shell-quote@1.6.1)
├── chokidar@1.7.0 (path-is-absolute@1.0.1, inherits@2.0.3, async-each@1.0.1, glob-parent@2.0.0, is-glob@2.0.1, is-binary-path@1.0.1, readdirp@2.1.0)
└── anymatch@1.3.2 (normalize-path@2.1.1, micromatch@2.3.11)
tape@4.9.1 node_modules/tape
├── inherits@2.0.3
├── has@1.0.3
├── defined@1.0.0
├── resumer@0.0.0
├── deep-equal@1.0.1
├── through@2.3.8
├── function-bind@1.1.1
├── minimist@1.2.0
├── object-inspect@1.6.0
├── for-each@0.3.3 (is-callable@1.1.4)
├── glob@7.1.2 (path-is-absolute@1.0.1, fs.realpath@1.0.0, inflight@1.0.6, once@1.4.0, minimatch@3.0.4)
├── resolve@1.7.1 (path-parse@1.0.6)
└── string.prototype.trim@1.1.2 (define-properties@1.1.3, es-abstract@1.12.0)
browserify@16.2.2 node_modules/browserify
├── inherits@2.0.3
├── tty-browserify@0.0.1
├── https-browserify@1.0.0
├── duplexer2@0.1.4
├── punycode@1.4.1
├── through2@2.0.3
├── constants-browserify@1.0.0
├── path-browserify@0.0.1
├── domain-browser@1.2.0
├── os-browserify@0.3.0
├── htmlescape@1.1.1
├── util@0.10.4
├── defined@1.0.0
├── process@0.11.10
├── xtend@4.0.1
├── stream-browserify@2.0.1
├── cached-path-relative@1.0.1
├── read-only-stream@2.0.0
├── querystring-es3@0.2.1
├── timers-browserify@1.4.2
├── vm-browserify@1.1.0
├── deps-sort@2.0.0
├── string_decoder@1.1.1 (safe-buffer@5.1.2)
├── concat-stream@1.6.2 (buffer-from@1.1.1, typedarray@0.0.6)
├── events@2.1.0
├── has@1.0.3 (function-bind@1.1.1)
├── parents@1.0.1 (path-platform@0.11.15)
├── buffer@5.2.0 (ieee754@1.1.12, base64-js@1.3.0)
├── shell-quote@1.6.1 (array-filter@0.0.1, array-reduce@0.0.0, jsonify@0.0.0, array-map@0.0.0)
├── console-browserify@1.1.0 (date-now@0.1.4)
├── subarg@1.0.0 (minimist@1.2.0)
├── url@0.11.0 (punycode@1.3.2, querystring@0.2.0)
├── readable-stream@2.3.6 (process-nextick-args@2.0.0, safe-buffer@5.1.2, util-deprecate@1.0.2, core-util-is@1.0.2, isarray@1.0.0)
├── labeled-stream-splicer@2.0.1 (isarray@2.0.4, stream-splicer@2.0.0)
├── glob@7.1.2 (path-is-absolute@1.0.1, fs.realpath@1.0.0, once@1.4.0, inflight@1.0.6, minimatch@3.0.4)
├── shasum@1.0.2 (json-stable-stringify@0.0.1, sha.js@2.4.11)
├── stream-http@2.8.3 (builtin-status-codes@3.0.0, to-arraybuffer@1.0.1)
├── assert@1.4.1 (util@0.10.3)
├── browserify-zlib@0.2.0 (pako@1.0.6)
├── JSONStream@1.3.4 (through@2.3.8, jsonparse@1.3.1)
├── syntax-error@1.4.0 (acorn-node@1.5.2)
├── browser-resolve@1.11.3 (resolve@1.1.7)
├── resolve@1.8.1 (path-parse@1.0.6)
├── browser-pack@6.1.0 (safe-buffer@5.1.2, umd@3.0.3, combine-source-map@0.8.0)
├── insert-module-globals@7.2.0 (path-is-absolute@1.0.1, is-buffer@1.1.6, undeclared-identifiers@1.1.2, acorn-node@1.5.2, combine-source-map@0.8.0)
├── crypto-browserify@3.12.0 (randomfill@1.0.4, randombytes@2.0.6, create-hmac@1.1.7, pbkdf2@3.0.16, diffie-hellman@5.0.3, create-hash@1.2.0, browserify-cipher@1.0.1, create-ecdh@4.0.3, browserify-sign@4.0.4, public-encrypt@4.0.2)
└── module-deps@6.1.0 (stream-combiner2@1.1.1, detective@5.1.0)
eslint@3.19.0 node_modules/eslint
├── path-is-inside@1.0.2
├── imurmurhash@0.1.4
├── strip-bom@3.0.0
├── natural-compare@1.4.0
├── strip-json-comments@2.0.1
├── pluralize@1.2.1
├── ignore@3.3.10
├── is-resolvable@1.1.0
├── estraverse@4.2.0
├── globals@9.18.0
├── esquery@1.0.1
├── esutils@2.0.2
├── progress@1.1.8
├── doctrine@2.1.0
├── text-table@0.2.0
├── user-home@2.0.0 (os-homedir@1.0.2)
├── babel-code-frame@6.26.0 (js-tokens@3.0.2)
├── debug@2.6.9 (ms@2.0.0)
├── chalk@1.1.3 (escape-string-regexp@1.0.5, ansi-styles@2.2.1, supports-color@2.0.0, has-ansi@2.0.0, strip-ansi@3.0.1)
├── json-stable-stringify@1.0.1 (jsonify@0.0.0)
├── optionator@0.8.2 (fast-levenshtein@2.0.6, type-check@0.3.2, wordwrap@1.0.0, deep-is@0.1.3, prelude-ls@1.1.2)
├── levn@0.3.0 (type-check@0.3.2, prelude-ls@1.1.2)
├── require-uncached@1.0.3 (resolve-from@1.0.1, caller-path@0.1.0)
├── glob@7.1.2 (path-is-absolute@1.0.1, inherits@2.0.3, fs.realpath@1.0.0, once@1.4.0, inflight@1.0.6, minimatch@3.0.4)
├── concat-stream@1.6.2 (inherits@2.0.3, buffer-from@1.1.1, typedarray@0.0.6, readable-stream@2.3.6)
├── inquirer@0.12.0 (ansi-regex@2.1.1, strip-ansi@3.0.1, ansi-escapes@1.4.0, cli-width@2.2.0, through@2.3.8, rx-lite@3.1.2, figures@1.7.0, string-width@1.0.2, readline2@1.0.1, run-async@0.1.0, cli-cursor@1.0.2)
├── is-my-json-valid@2.19.0 (jsonpointer@4.0.1, generate-function@2.0.0, xtend@4.0.1, is-my-ip-valid@1.0.0, generate-object-property@1.2.0)
├── file-entry-cache@2.0.0 (object-assign@4.1.1, flat-cache@1.3.0)
├── espree@3.5.4 (acorn@5.7.1, acorn-jsx@3.0.1)
├── js-yaml@3.12.0 (esprima@4.0.1, argparse@1.0.10)
├── shelljs@0.7.8 (interpret@1.1.0, rechoir@0.6.2)
├── table@3.8.3 (slice-ansi@0.0.4, ajv-keywords@1.5.1, string-width@2.1.1, ajv@4.11.8)
├── escope@3.6.0 (esrecurse@4.2.1, es6-weak-map@2.0.2, es6-map@0.1.5)
└── lodash@4.17.10
updtr@2.0.0 node_modules/updtr
├── ansi-escapes@2.0.0
├── pify@3.0.0
├── cli-spinners@1.3.1
├── unicons@0.0.3
├── es6-error@4.1.1
├── semver@5.5.1
├── string-width@2.1.1 (is-fullwidth-code-point@2.0.0, strip-ansi@4.0.0)
├── chalk@1.1.3 (escape-string-regexp@1.0.5, ansi-styles@2.2.1, supports-color@2.0.0, has-ansi@2.0.0, strip-ansi@3.0.1)
├── cli-cursor@2.1.0 (restore-cursor@2.0.0)
├── yargs@8.0.2 (get-caller-file@1.0.3, decamelize@1.2.0, y18n@3.2.1, camelcase@4.1.0, set-blocking@2.0.0, which-module@2.0.0, yargs-parser@7.0.0, require-main-filename@1.0.1, require-directory@2.1.1, cliui@3.2.0, os-locale@2.1.0, read-pkg-up@2.0.0)
└── babel-runtime@6.26.0 (regenerator-runtime@0.11.1, core-js@2.5.7)
testcafe@0.21.1 node_modules/testcafe
├── pify@2.3.0
├── read-file-relative@1.2.0
├── elegant-spinner@1.0.1
├── node-version@1.2.0
├── map-reverse@1.0.1
├── resolve-from@4.0.0
├── pinkie@2.0.4
├── replicator@1.0.2
├── time-limit-promise@1.0.4
├── dedent@0.4.0
├── testcafe-reporter-minimal@2.1.0
├── testcafe-reporter-list@2.1.0
├── testcafe-reporter-json@2.1.0
├── testcafe-reporter-spec@2.1.1
├── testcafe-reporter-xunit@2.1.0
├── babel-plugin-transform-runtime@6.23.0
├── async-exit-hook@1.1.2
├── graceful-fs@4.1.11
├── callsite@1.0.0
├── os-family@1.0.0
├── commander@2.17.1
├── chrome-emulated-devices-list@0.1.1
├── tree-kill@1.2.0
├── bin-v8-flags-filter@1.1.3
├── nanoid@1.2.1
├── is-glob@2.0.1 (is-extglob@1.0.0)
├── mustache@2.3.2
├── moment-duration-format@2.2.2
├── resolve-cwd@1.0.0 (resolve-from@2.0.0)
├── qrcode-terminal@0.10.0
├── strip-bom@2.0.0 (is-utf8@0.2.1)
├── promisify-event@1.0.0 (pinkie-promise@2.0.1)
├── is-ci@1.2.0 (ci-info@1.3.1)
├── pngjs@3.3.3
├── chalk@1.1.3 (escape-string-regexp@1.0.5, ansi-styles@2.2.1, supports-color@2.0.0, strip-ansi@3.0.1, has-ansi@2.0.0)
├── parse5@1.5.1
├── debug@2.6.9 (ms@2.0.0)
├── endpoint-utils@1.0.2 (ip@1.1.5, pinkie-promise@1.0.0)
├── babel-preset-flow@6.23.0 (babel-plugin-transform-flow-strip-types@6.22.0)
├── tmp@0.0.28 (os-tmpdir@1.0.2)
├── error-stack-parser@1.3.6 (stackframe@0.3.1)
├── useragent@2.3.0 (lru-cache@4.1.3)
├── source-map-support@0.5.8 (buffer-from@1.1.1, source-map@0.6.1)
├── indent-string@1.2.2 (get-stdin@4.0.1, minimist@1.2.0, repeating@1.1.3)
├── sanitize-filename@1.6.1 (truncate-utf8-bytes@1.0.2)
├── log-update-async-hook@2.0.2 (ansi-escapes@2.0.0, onetime@2.0.1, wrap-ansi@2.1.0)
├── globby@3.0.1 (arrify@1.0.1, object-assign@4.1.1, pinkie-promise@1.0.0, array-union@1.0.2, glob@5.0.15)
├── ps-node@0.1.6 (table-parser@0.1.3)
├── gulp-data@1.3.1 (util-extend@1.0.3, plugin-error@0.1.2, through2@2.0.3)
├── chai@3.5.0 (assertion-error@1.1.0, type-detect@1.0.0, deep-eql@0.1.3)
├── chrome-remote-interface@0.25.7 (commander@2.11.0, ws@3.3.3)
├── babel-plugin-transform-class-properties@6.24.1 (babel-plugin-syntax-class-properties@6.13.0, babel-helper-function-name@6.24.1, babel-template@6.26.0)
├── babel-preset-stage-2@6.24.1 (babel-plugin-syntax-dynamic-import@6.18.0, babel-plugin-transform-decorators@6.24.1, babel-preset-stage-3@6.24.1)
├── testcafe-hammerhead@14.2.4 (pinkie@1.0.0, webauth@1.1.0, semver@5.5.0, crypto-md5@1.0.0, lru-cache@2.6.3, mime@1.4.1, nanoid@0.2.2, yakaa@1.0.1, tunnel-agent@0.6.0, match-url-wildcard@0.0.2, bowser@1.6.0, tough-cookie@2.3.3, iconv-lite@0.4.11, merge-stream@1.0.1, brotli@1.3.2, gulp-run-command@0.0.9, gulp-clone@2.0.1, css@2.2.3)
├── moment@2.22.2
├── typescript@2.9.2
├── callsite-record@4.1.3 (pinkie-promise@2.0.1, @types/error-stack-parser@1.3.18, highlight-es@1.0.3, chalk@2.4.1, @types/lodash@4.14.116)
├── babel-preset-env@1.7.0 (babel-plugin-syntax-trailing-function-commas@6.22.0, babel-plugin-transform-es2015-for-of@6.23.0, babel-plugin-transform-es2015-destructuring@6.23.0, babel-plugin-transform-es2015-arrow-functions@6.22.0, babel-plugin-check-es2015-constants@6.22.0, babel-plugin-transform-es2015-spread@6.22.0, babel-plugin-transform-es2015-template-literals@6.22.0, babel-plugin-transform-es2015-literals@6.22.0, babel-plugin-transform-es2015-block-scoped-functions@6.22.0, babel-plugin-transform-es2015-typeof-symbol@6.23.0, semver@5.5.1, invariant@2.2.4, babel-plugin-transform-es2015-shorthand-properties@6.24.1, babel-plugin-transform-es2015-duplicate-keys@6.24.1, babel-plugin-transform-es2015-sticky-regex@6.24.1, babel-plugin-transform-es2015-unicode-regex@6.24.1, babel-plugin-transform-es2015-block-scoping@6.26.0, babel-plugin-transform-es2015-parameters@6.24.1, babel-plugin-transform-es2015-classes@6.24.1, babel-plugin-transform-regenerator@6.26.0, babel-plugin-transform-es2015-function-name@6.24.1, babel-plugin-transform-es2015-modules-umd@6.24.1, babel-plugin-transform-es2015-computed-properties@6.24.1, babel-plugin-transform-es2015-modules-amd@6.24.1, babel-plugin-transform-es2015-modules-commonjs@6.26.2, babel-plugin-transform-es2015-modules-systemjs@6.24.1, babel-plugin-transform-async-to-generator@6.24.1, babel-plugin-transform-es2015-object-super@6.24.1, babel-plugin-transform-exponentiation-operator@6.24.1, browserslist@3.2.8)
├── lodash@4.17.10
├── testcafe-legacy-api@3.1.7 (dedent@0.6.0, async@0.2.6, parse5@2.2.3, highlight-es@1.0.3, babel-runtime@5.8.38)
├── testcafe-browser-tools@1.6.4 (linux-platform-info@0.0.3, array-find@1.0.0, which-promise@1.0.0, babel-runtime@5.8.38)
├─��� babel-core@6.26.3 (path-is-absolute@1.0.1, slash@1.0.0, babel-template@6.26.0, babel-messages@6.23.0, private@0.1.8, convert-source-map@1.5.1, babel-helpers@6.24.1, json5@0.5.1, babylon@6.18.0, babel-code-frame@6.26.0, source-map@0.5.7, minimatch@3.0.4, babel-types@6.26.0, babel-traverse@6.26.0, babel-generator@6.26.1, babel-register@6.26.0)
└── babel-runtime@6.26.0 (regenerator-runtime@0.11.1, core-js@2.5.7)
9.88s$ npm test
> cuid@2.1.2 test /home/travis/build/ericelliott/cuid
> npm run lint && npm run test:server && npm run test:browser
> cuid@2.1.2 lint /home/travis/build/ericelliott/cuid
> eslint index.js lib test
> cuid@2.1.2 test:server /home/travis/build/ericelliott/cuid
> tape test/server.js
TAP version 13
# cuid()
ok 1 cuid() should return a string.
# cuid.slug()
ok 2 cuid.slug() should return a string.
ok 3 cuid.slug() cuids should not collide.
# cuid.isCuid()
ok 4 cuid.isCuid() should return true for a valid cuid.
ok 5 cuid.isCuid() should return false for null.
ok 6 cuid.isCuid() should return false for undefined.
ok 7 cuid.isCuid() should return false for a random string.
ok 8 cuid.isCuid() should return false for numbers.
ok 9 cuid.isCuid() should return false for NaN.
# cuid.isSlug()
ok 10 cuid.isSlug() should return true for a valid cuid slug.
ok 11 cuid.isSlug() should return false for null.
ok 12 cuid.isSlug() should return false for undefined.
ok 13 cuid.isSlug() should return false for numbers.
ok 14 cuid.isSlug() should return false for NaN.
# cuid colissions
ok 15 cuids should not collide.
1..15
# tests 15
# pass  15
# ok
> cuid@2.1.2 test:browser /home/travis/build/ericelliott/cuid
> testcafe chrome ./test/browser.js
/home/travis/build/ericelliott/cuid/node_modules/testcafe/lib/cli/cli.js:56
    var _ref2 = (0, _asyncToGenerator3.default)(function* (providerName = 'locally-installed') {
                                                                        ^
SyntaxError: Unexpected token =
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at loader (/home/travis/build/ericelliott/cuid/node_modules/testcafe/lib/cli/index.js:27:5)
    at Object.<anonymous> (/home/travis/build/ericelliott/cuid/node_modules/testcafe/lib/cli/index.js:28:3)
    at Module._compile (module.js:409:26)
```

**Comment by kennylavender** [comment]
Now getting this Error with node 8/9: `ERROR Unable to establish one or more of the specified browser connections. This can be caused by network issues or remote device failure.`

**Comment by kennylavender** [comment]
Don't merge, found an issue with the browser tests, if I create a failing test, this gets thrown, but does not cause the tests to fail.

```
(node:17095) UnhandledPromiseRejectionWarning: #<ExternalAssertionLibraryError>
(node:17095) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
```

**Comment by ericelliott** [comment]
Feel free to merge when you feel ready.

**Comment by kennylavender** [comment]
`security/snyk` is stuck, going to push a commit to fix it.

**Pull request merged**
