### PR TITLE
Object.keys() doesn't work in IE8

### PR DESCRIPTION
**Pull request by bengourley**
I know in the readme you mention explicitely that IE9+ is supported. However, we depend on this module for [bugsnag-js](https://github.com/bugsnag/bugsnag-js) and we need to support IE8 for our customers.

It turns out it's a pretty small change to support IE8, so I wondered if you wouldn't mind merging? Otherwise, I understand and we'll just have to maintain a fork 😢

### CODE REVIEW

**Comment by MarkHerhold** [comment]
I personally don't this should be merged (let old browsers die) but if it does, it needs comments otherwise someone is bound to optimize it out again.

**Comment by bengourley** [comment]
> let old browsers die

I agree, but unfortunately we can't make that decision on behalf of our customers 😣 (we only dropped IE 6/7 support for our notifier in December!)

> it needs comments

Good idea, happy to do this if it will get merged.

**Comment by ericelliott** [comment]
Shouldn't you polyfill Object.keys for your clients if it doesn't exist, instead?

**Comment by ericelliott** [comment]
https://polyfill.io/v2/docs/

**Comment by bengourley** [comment]
I'd also love to polyfill it, but we can't alter the global environment for our users either. I will just have to maintain a fork. Thanks for taking a look at the PR anyway and I understand your reasons for not merging.

**Comment by ericelliott** [comment]
> I'd also love to polyfill it, but we can't alter the global environment for our users either.

The primary reason many teams have a policy of not altering the global environment is because doing so could make the app incompatible with future versions of JavaScript and the browser engines.

*The only reason not to polyfill a standardized feature is because somebody ALREADY HAS altered the global environment in incompatible ways.* 

In other words, if you can't polyfill standardized features for your users, not only are you stuck supporting IE8, **those users are forever stuck with IE8** unless somebody refactors those now incompatible changes. Your problems run much deeper than maintaining a fork of a small library.

**Comment by bengourley** [comment]
I'm fully on-board with reasons to polyfill, in fact I advocated the approach of shipping bugsnag-js to expect an ES5 environment, pushing the responsibility of shimming/polyfilling the built-in prototypes (if they wanted to support pre-ES5 browsers) on to the developer. In most scenarios, people supporting older browsers are going to be doing that anyway.

However, from a different perspective Bugsnag needs to be as frictionless as possible for people to adopt, and from a business pov we take on the burden of being able to run in sub-optimal conditions – conditions that you or I would not recommend! For a concrete example, we have a customer whose frontend JS does not allow any modifications to the global environment, and it has a set of tests which actively fail if anything modifies a built-in prototype. Being agnostic about engineering choices like this means that we remove barriers to entry and hopefully increase adoption. The downsides are that we may occasionally have to maintain a fork of some libraries, and have our own [shimmed subset of modern features](https://github.com/bugsnag/bugsnag-js/blob/master/base/lib/es-utils.js) that we use, but the tradeoffs seem manageable for now.

**Pull request closed without merging**
