### PR TITLE
Modernize & cleanup (#72)

### PR DESCRIPTION
**Pull request by MarkHerhold**
This is a continuation of @gmaclennan's excellent modernization work in #72. In this PR, I'm removing zuul and SauceLabs due to stability issues in favor of testing with Karma in headless Chrome.

Note that I chose not to use puppeteer to manage headless chrome because puppeteer is currently not compatible with Node.js v4 LTS.

### CODE REVIEW

**Comment by ericelliott** [comment]
Assuming tests pass, this looks OK to me.

**Comment by ericelliott** [comment]
Please be sure to resolve conflicts with master so we can merge safely.

**Comment by MarkHerhold** [comment]
@ericelliott Done 👍

**Comment by MarkHerhold** [comment]
Obviously this is still flaky though. :(

**Comment by MarkHerhold** [comment]
@ericelliott I think the reason we are seeing browser failures is because of the collision tests. I've disabled it for now.

**Comment by gmaclennan** [comment]
@MarkHerhold we should probably open an issue for failing collision tests in the browser? Any ideas of how/where it is failing?

**Comment by ericelliott** [comment]
@gmaclennan I think it's just timing out intermittently

**Pull request merged**
