### PR TITLE
Add slug() method definition

### PR DESCRIPTION
**Pull request by whitecolor**

### CODE REVIEW

**Comment by paambaati** [comment]
@whitecolor Once https://github.com/whitecolor/cuid/pull/1 gets merged, this PR can land.

**Comment by paambaati** [comment]
@ericelliott Can we get this merged? Anything else I can help with?

**Comment by ericelliott** [comment]
Pushed as v2.1.0 -- please test and let me know if it works for you

**Comment by whitecolor** [comment]
Hm, there is only 2.0.2 on npm and it contains old `index.d.ts`

**Comment by paambaati** [comment]
@ericelliott `2.1.0` isn't published yet; the latest version on NPM is still `2.0.2`.

**Comment by whitecolor** [comment]
Ok so I will check npm version. I believe there should be no problem.

**Comment by ericelliott** [comment]
Sorry. Published. Please test.

**Comment by paambaati** [comment]
@ericelliott @whitecolor Works now, thanks!

**Pull request merged**
